name = "nearby724"
type = "javascript"

# Specify your Cloudflare account ID
account_id = "310e549bbc8846e19ec8b3bd662d5f00"  # Replace with your actual Cloudflare account ID

[build]
command = "npm run build"  # Command to build your project
output_dir = "dist"         # Directory where the built files are located

# Optional: Specify the compatibility date for your project
compatibility_date = "2024-12-03"

# Optional: Add any additional configuration as needed
