name = "nearby"
type = "javascript"

[build]
command = "npm run build"
output_dir = "dist"

# If you are using Cloudflare Pages for the frontend
[[pages]]
name = "nearby"
path = "dist" # the output directory for your build
